DROP TABLE IF EXISTS `#__xius_cache`;;

CREATE TABLE IF NOT EXISTS `#__xius_cache` (
  `userid` int(21) NOT NULL,
  `joomlaemail_0` varchar(250) NOT NULL,
  `jsfields11_0` varchar(250) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;;

INSERT INTO `#__xius_cache` (`userid`, `joomlaemail_0`, `jsfields11_0`) VALUES
(62, 'gaurav.jain028@gmail.com', 'Bhilwara'),
(63, 'gaurav@readybytes.in', 'Ajmer'),
(64, 'vikas@readybytes.in', 'Surat'),
(65, 'username66@email.com', 'Ludhiana'),
(66, 'username67@email.com', 'Chandigarh'),
(67, 'username68@email.com', 'Indore'),
(68, 'username69@email.com', 'Noida'),
(69, 'username70@email.com', 'Shimla'),
(70, 'username71@email.com', 'Pune'),
(71, 'username72@email.com', 'Kolkata'),
(72, 'username73@email.com', 'Alwar'),
(73, 'username74@email.com', 'Pune'),
(74, 'username75@email.com', 'Noida'),
(75, 'username76@email.com', 'Ajmer'),
(76, 'username77@email.com', 'Noida'),
(77, 'username78@email.com', 'Ludhiana'),
(78, 'username79@email.com', 'Bikaner'),
(79, 'username80@email.com', 'Nagpur'),
(80, 'username81@email.com', 'chennai'),
(81, 'username82@email.com', 'Ahmedabad'),
(82, 'username83@email.com', 'Coimbatore'),
(83, 'username84@email.com', 'Nagpur'),
(84, 'username85@email.com', 'Bhilwara'),
(85, 'username86@email.com', 'Ludhiana'),
(86, 'username87@email.com', 'Jalandhar'),
(87, 'username88@email.com', 'Jodhapur'),
(88, 'username89@email.com', 'Ludhiana'),
(89, 'username90@email.com', 'Alwar'),
(90, 'username91@email.com', 'Bhilwara'),
(91, 'username92@email.com', 'Indore'),
(92, 'username93@email.com', 'Noida'),
(93, 'username94@email.com', 'Indore'),
(94, 'username95@email.com', 'Kolkata'),
(95, 'username96@email.com', 'Nagpur'),
(96, 'username97@email.com', 'Jaipur'),
(97, 'username98@email.com', 'Bhopal'),
(98, 'username99@email.com', 'Mumbai'),
(99, 'username100@email.com', 'Ludhiana'),
(100, 'username101@email.com', 'Ludhiana'),
(101, 'username102@email.com', 'Ajmer'),
(102, 'username103@email.com', 'Coimbatore'),
(103, 'username104@email.com', 'Pune'),
(104, 'username105@email.com', 'Vadodara'),
(105, 'username106@email.com', 'Bikaner'),
(106, 'username107@email.com', 'Hyderabad'),
(107, 'username108@email.com', 'chennai'),
(108, 'username109@email.com', 'Bhilwara'),
(109, 'username110@email.com', 'Udaipur'),
(110, 'username111@email.com', 'chennai'),
(111, 'username112@email.com', 'Jaipur'),
(112, 'username113@email.com', 'Ahmedabad'),
(113, 'username114@email.com', 'Jalandhar'),
(114, 'username115@email.com', 'Hyderabad'),
(115, 'username116@email.com', 'Bhilwara'),
(116, 'username117@email.com', 'Shimla'),
(117, 'username118@email.com', 'Banglore'),
(118, 'username119@email.com', 'Jaipur'),
(119, 'username120@email.com', 'Surat'),
(120, 'username121@email.com', 'Ludhiana');;

TRUNCATE TABLE `#__xius_info`;;
INSERT INTO `#__xius_info` (`id`, `labelName`, `params`, `key`, `pluginParams`, `pluginType`, `ordering`, `published`) VALUES
(23, 'Send Email', 'isSearchable=1\nisVisible=0\nisSortable=1\nisExportable=0\ntooltip=\n\n', 'Email', 'xius_email=21\n\n', 'Xiusemail', 3, 1),
(21, 'E-mail', 'isSearchable=1\nisVisible=1\nisSortable=1\nisExportable=0\ntooltip=\n\n', 'email', '', 'Joomla', 1, 1),
(22, 'City / Town', 'isSearchable=1\nisVisible=1\nisSortable=1\nisExportable=0\ntooltip=\n\n', '11', '', 'Jsfields', 2, 1);;

